defaults:
  - train: default
  - policy: small
  - prior: default
  - hydra: default
  - wandb: default
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

prior:
  num_actions: 5
  init_alpha: 1.
  init_beta: 1.

policy:
  num_actions: ${prior.num_actions}
  horizon: 30
  drop_p: 0.

train:
  policy_lr: 1e-4
  prior_lr: 1e-4
  monte_carlo_samples: 256
  epochs: 5000
  batch_size: 256

save_every_steps: 1000
keep_every_steps: 10000

seed: 1234
out_dir: output/runs

fix_prior: true

test_run: False
